import type { Theme, ThemeName } from './types.js';

export const modernTheme: Theme = {
  name: 'modern',
  displayName: 'Modern',
  colors: {
    primary: 'green',
    secondary: 'cyan',
    accent: 'yellow',
    muted: 'gray',
    border: 'gray',
    borderActive: 'cyan',
    statusInbox: 'blue',
    statusNext: 'green',
    statusWaiting: 'yellow',
    statusSomeday: 'magenta',
    statusDone: 'gray',
    text: 'white',
    textMuted: 'gray',
    textSelected: 'cyan',
    textHighlight: 'green',
    fnKeyLabel: 'black',
    fnKeyText: 'cyan',
  },
  borders: {
    main: 'single',
    modal: 'round',
    list: 'single',
  },
  style: {
    selectedPrefix: '› ',
    unselectedPrefix: '  ',
    tabActiveInverse: true,
    tabBrackets: ['', ''],
    headerUppercase: false,
    showFunctionKeys: false,
    loadingChars: ['▪', '▫'],
  },
};

export const nortonCommanderTheme: Theme = {
  name: 'norton-commander',
  displayName: 'Norton Commander',
  colors: {
    primary: 'cyan',
    secondary: 'yellow',
    accent: 'white',
    muted: 'blue',
    border: 'cyan',
    borderActive: 'yellow',
    background: 'blue',
    statusInbox: 'white',
    statusNext: 'green',
    statusWaiting: 'yellow',
    statusSomeday: 'magenta',
    statusDone: 'gray',
    text: 'cyan',
    textMuted: 'blue',
    textSelected: 'yellow',
    textHighlight: 'white',
    fnKeyLabel: 'cyan',
    fnKeyText: 'white',
  },
  borders: {
    main: 'double',
    modal: 'double',
    list: 'double',
  },
  style: {
    selectedPrefix: '► ',
    unselectedPrefix: '  ',
    tabActiveInverse: true,
    tabBrackets: ['[', ']'],
    headerUppercase: true,
    showFunctionKeys: true,
    loadingChars: ['█', '░'],
  },
};

export const dosPromptTheme: Theme = {
  name: 'dos-prompt',
  displayName: 'DOS Prompt',
  colors: {
    primary: 'green',
    secondary: 'green',
    accent: 'white',
    muted: 'gray',
    border: 'green',
    borderActive: 'white',
    statusInbox: 'white',
    statusNext: 'green',
    statusWaiting: 'yellow',
    statusSomeday: 'gray',
    statusDone: 'gray',
    text: 'green',
    textMuted: 'gray',
    textSelected: 'white',
    textHighlight: 'green',
    fnKeyLabel: 'green',
    fnKeyText: 'white',
  },
  borders: {
    main: 'single',
    modal: 'single',
    list: 'single',
  },
  style: {
    selectedPrefix: '> ',
    unselectedPrefix: '  ',
    tabActiveInverse: false,
    tabBrackets: ['<', '>'],
    headerUppercase: true,
    showFunctionKeys: true,
    loadingChars: ['#', '-'],
  },
};

export const turboPascalTheme: Theme = {
  name: 'turbo-pascal',
  displayName: 'Turbo Pascal IDE',
  colors: {
    primary: 'yellow',
    secondary: 'white',
    accent: 'red',
    muted: 'cyan',
    border: 'white',
    borderActive: 'yellow',
    background: 'blue',
    statusInbox: 'white',
    statusNext: 'yellow',
    statusWaiting: 'red',
    statusSomeday: 'cyan',
    statusDone: 'gray',
    text: 'white',
    textMuted: 'cyan',
    textSelected: 'yellow',
    textHighlight: 'white',
    fnKeyLabel: 'red',
    fnKeyText: 'cyan',
  },
  borders: {
    main: 'double',
    modal: 'double',
    list: 'single',
  },
  style: {
    selectedPrefix: '» ',
    unselectedPrefix: '  ',
    tabActiveInverse: true,
    tabBrackets: ['[', ']'],
    headerUppercase: true,
    showFunctionKeys: true,
    loadingChars: ['█', '▒'],
  },
};

// Classic Macintosh System 7 style - monochrome elegance
export const classicMacTheme: Theme = {
  name: 'classic-mac',
  displayName: 'Classic Mac',
  colors: {
    primary: 'white',
    secondary: 'white',
    accent: 'white',
    muted: 'gray',
    border: 'white',
    borderActive: 'white',
    statusInbox: 'white',
    statusNext: 'white',
    statusWaiting: 'gray',
    statusSomeday: 'gray',
    statusDone: 'gray',
    text: 'white',
    textMuted: 'gray',
    textSelected: 'black',
    textHighlight: 'white',
    fnKeyLabel: 'black',
    fnKeyText: 'white',
  },
  borders: {
    main: 'single',
    modal: 'round',
    list: 'single',
  },
  style: {
    selectedPrefix: '☛ ',
    unselectedPrefix: '  ',
    tabActiveInverse: true,
    tabBrackets: ['', ''],
    headerUppercase: false,
    showFunctionKeys: false,
    loadingChars: ['◼', '◻'],
  },
};

// Apple II green phosphor monitor
export const appleIITheme: Theme = {
  name: 'apple-ii',
  displayName: 'Apple ][',
  colors: {
    primary: '#00ff00',
    secondary: '#00ff00',
    accent: '#00ff00',
    muted: '#008000',
    border: '#00ff00',
    borderActive: '#00ff00',
    statusInbox: '#00ff00',
    statusNext: '#00ff00',
    statusWaiting: '#008000',
    statusSomeday: '#008000',
    statusDone: '#004000',
    text: '#00ff00',
    textMuted: '#008000',
    textSelected: '#00ff00',
    textHighlight: '#00ff00',
    fnKeyLabel: '#004000',
    fnKeyText: '#00ff00',
  },
  borders: {
    main: 'single',
    modal: 'single',
    list: 'single',
  },
  style: {
    selectedPrefix: '] ',
    unselectedPrefix: '  ',
    tabActiveInverse: true,
    tabBrackets: ['[', ']'],
    headerUppercase: true,
    showFunctionKeys: false,
    loadingChars: ['▓', '░'],
  },
};

// Commodore 64 - iconic blue and light blue
export const commodore64Theme: Theme = {
  name: 'commodore-64',
  displayName: 'Commodore 64',
  colors: {
    primary: '#7869c4',
    secondary: '#9f9fff',
    accent: '#ffffff',
    muted: '#6c5eb5',
    border: '#7869c4',
    borderActive: '#9f9fff',
    background: '#40318d',
    statusInbox: '#9f9fff',
    statusNext: '#7fff7f',
    statusWaiting: '#ffff7f',
    statusSomeday: '#7f7fff',
    statusDone: '#6c5eb5',
    text: '#9f9fff',
    textMuted: '#6c5eb5',
    textSelected: '#ffffff',
    textHighlight: '#9f9fff',
    fnKeyLabel: '#40318d',
    fnKeyText: '#9f9fff',
  },
  borders: {
    main: 'single',
    modal: 'single',
    list: 'single',
  },
  style: {
    selectedPrefix: '▶ ',
    unselectedPrefix: '  ',
    tabActiveInverse: true,
    tabBrackets: ['<', '>'],
    headerUppercase: true,
    showFunctionKeys: true,
    loadingChars: ['●', '○'],
  },
};

// Amiga Workbench - orange, blue, white, black
export const amigaWorkbenchTheme: Theme = {
  name: 'amiga-workbench',
  displayName: 'Amiga Workbench',
  colors: {
    primary: '#ff8800',
    secondary: '#0055aa',
    accent: '#ffffff',
    muted: '#0055aa',
    border: '#ff8800',
    borderActive: '#ffffff',
    background: '#0055aa',
    statusInbox: '#ffffff',
    statusNext: '#ff8800',
    statusWaiting: '#ffcc00',
    statusSomeday: '#0088ff',
    statusDone: '#555555',
    text: '#ff8800',
    textMuted: '#0088ff',
    textSelected: '#ffffff',
    textHighlight: '#ff8800',
    fnKeyLabel: '#0055aa',
    fnKeyText: '#ff8800',
  },
  borders: {
    main: 'double',
    modal: 'single',
    list: 'single',
  },
  style: {
    selectedPrefix: '▸ ',
    unselectedPrefix: '  ',
    tabActiveInverse: true,
    tabBrackets: ['【', '】'],
    headerUppercase: false,
    showFunctionKeys: true,
    loadingChars: ['▰', '▱'],
  },
};

// Matrix - digital rain aesthetic
export const matrixTheme: Theme = {
  name: 'matrix',
  displayName: 'Matrix',
  colors: {
    primary: '#00ff00',
    secondary: '#00cc00',
    accent: '#ffffff',
    muted: '#003300',
    border: '#00ff00',
    borderActive: '#00ff00',
    statusInbox: '#00ff00',
    statusNext: '#00ff00',
    statusWaiting: '#00cc00',
    statusSomeday: '#009900',
    statusDone: '#003300',
    text: '#00ff00',
    textMuted: '#006600',
    textSelected: '#ffffff',
    textHighlight: '#00ff00',
    fnKeyLabel: '#003300',
    fnKeyText: '#00ff00',
  },
  borders: {
    main: 'single',
    modal: 'single',
    list: 'single',
  },
  style: {
    selectedPrefix: '⟩ ',
    unselectedPrefix: '  ',
    tabActiveInverse: false,
    tabBrackets: ['⟨', '⟩'],
    headerUppercase: false,
    showFunctionKeys: false,
    loadingChars: ['█', '▁'],
  },
};

// Amber CRT monitor
export const amberCrtTheme: Theme = {
  name: 'amber-crt',
  displayName: 'Amber CRT',
  colors: {
    primary: '#ffb000',
    secondary: '#ffb000',
    accent: '#ffd000',
    muted: '#805800',
    border: '#ffb000',
    borderActive: '#ffd000',
    statusInbox: '#ffd000',
    statusNext: '#ffb000',
    statusWaiting: '#cc8800',
    statusSomeday: '#996600',
    statusDone: '#664400',
    text: '#ffb000',
    textMuted: '#996600',
    textSelected: '#ffd000',
    textHighlight: '#ffb000',
    fnKeyLabel: '#664400',
    fnKeyText: '#ffb000',
  },
  borders: {
    main: 'single',
    modal: 'single',
    list: 'single',
  },
  style: {
    selectedPrefix: '→ ',
    unselectedPrefix: '  ',
    tabActiveInverse: true,
    tabBrackets: ['(', ')'],
    headerUppercase: true,
    showFunctionKeys: false,
    loadingChars: ['▮', '▯'],
  },
};

// Phosphor CRT with glow effect colors
export const phosphorTheme: Theme = {
  name: 'phosphor',
  displayName: 'Phosphor',
  colors: {
    primary: '#33ff33',
    secondary: '#66ff66',
    accent: '#99ff99',
    muted: '#116611',
    border: '#33ff33',
    borderActive: '#66ff66',
    statusInbox: '#66ff66',
    statusNext: '#33ff33',
    statusWaiting: '#99ff33',
    statusSomeday: '#33ff99',
    statusDone: '#116611',
    text: '#33ff33',
    textMuted: '#228822',
    textSelected: '#99ff99',
    textHighlight: '#66ff66',
    fnKeyLabel: '#116611',
    fnKeyText: '#33ff33',
  },
  borders: {
    main: 'round',
    modal: 'round',
    list: 'single',
  },
  style: {
    selectedPrefix: '◈ ',
    unselectedPrefix: '  ',
    tabActiveInverse: true,
    tabBrackets: ['', ''],
    headerUppercase: false,
    showFunctionKeys: false,
    loadingChars: ['◉', '◎'],
  },
};

// Solarized Dark - eye-friendly classic
export const solarizedDarkTheme: Theme = {
  name: 'solarized-dark',
  displayName: 'Solarized Dark',
  colors: {
    primary: '#268bd2',
    secondary: '#2aa198',
    accent: '#b58900',
    muted: '#586e75',
    border: '#586e75',
    borderActive: '#268bd2',
    background: '#002b36',
    statusInbox: '#268bd2',
    statusNext: '#859900',
    statusWaiting: '#b58900',
    statusSomeday: '#6c71c4',
    statusDone: '#586e75',
    text: '#839496',
    textMuted: '#586e75',
    textSelected: '#93a1a1',
    textHighlight: '#268bd2',
    fnKeyLabel: '#073642',
    fnKeyText: '#839496',
  },
  borders: {
    main: 'round',
    modal: 'round',
    list: 'single',
  },
  style: {
    selectedPrefix: '• ',
    unselectedPrefix: '  ',
    tabActiveInverse: true,
    tabBrackets: ['', ''],
    headerUppercase: false,
    showFunctionKeys: false,
    loadingChars: ['●', '○'],
  },
};

// Solarized Light
export const solarizedLightTheme: Theme = {
  name: 'solarized-light',
  displayName: 'Solarized Light',
  colors: {
    primary: '#268bd2',
    secondary: '#2aa198',
    accent: '#b58900',
    muted: '#93a1a1',
    border: '#93a1a1',
    borderActive: '#268bd2',
    background: '#fdf6e3',
    statusInbox: '#268bd2',
    statusNext: '#859900',
    statusWaiting: '#b58900',
    statusSomeday: '#6c71c4',
    statusDone: '#93a1a1',
    text: '#657b83',
    textMuted: '#93a1a1',
    textSelected: '#586e75',
    textHighlight: '#268bd2',
    fnKeyLabel: '#eee8d5',
    fnKeyText: '#657b83',
  },
  borders: {
    main: 'round',
    modal: 'round',
    list: 'single',
  },
  style: {
    selectedPrefix: '• ',
    unselectedPrefix: '  ',
    tabActiveInverse: true,
    tabBrackets: ['', ''],
    headerUppercase: false,
    showFunctionKeys: false,
    loadingChars: ['●', '○'],
  },
};

// Synthwave / Outrun - neon 80s aesthetic
export const synthwaveTheme: Theme = {
  name: 'synthwave',
  displayName: 'Synthwave',
  colors: {
    primary: '#ff00ff',
    secondary: '#00ffff',
    accent: '#ff00aa',
    muted: '#660066',
    border: '#ff00ff',
    borderActive: '#00ffff',
    background: '#1a0a2e',
    statusInbox: '#00ffff',
    statusNext: '#ff00ff',
    statusWaiting: '#ffff00',
    statusSomeday: '#ff6600',
    statusDone: '#660066',
    text: '#ff00ff',
    textMuted: '#9933ff',
    textSelected: '#00ffff',
    textHighlight: '#ff00ff',
    fnKeyLabel: '#330033',
    fnKeyText: '#00ffff',
  },
  borders: {
    main: 'double',
    modal: 'double',
    list: 'single',
  },
  style: {
    selectedPrefix: '◆ ',
    unselectedPrefix: '  ',
    tabActiveInverse: true,
    tabBrackets: ['「', '」'],
    headerUppercase: false,
    showFunctionKeys: true,
    loadingChars: ['◢', '◣'],
  },
};

// Paper - light minimal theme
export const paperTheme: Theme = {
  name: 'paper',
  displayName: 'Paper',
  colors: {
    primary: '#333333',
    secondary: '#555555',
    accent: '#0066cc',
    muted: '#999999',
    border: '#cccccc',
    borderActive: '#333333',
    background: '#ffffff',
    statusInbox: '#0066cc',
    statusNext: '#009933',
    statusWaiting: '#cc6600',
    statusSomeday: '#666699',
    statusDone: '#999999',
    text: '#333333',
    textMuted: '#999999',
    textSelected: '#000000',
    textHighlight: '#0066cc',
    fnKeyLabel: '#eeeeee',
    fnKeyText: '#333333',
  },
  borders: {
    main: 'single',
    modal: 'round',
    list: 'single',
  },
  style: {
    selectedPrefix: '▸ ',
    unselectedPrefix: '  ',
    tabActiveInverse: false,
    tabBrackets: ['', ''],
    headerUppercase: false,
    showFunctionKeys: false,
    loadingChars: ['■', '□'],
  },
};

// Coffee - warm brown tones
export const coffeeTheme: Theme = {
  name: 'coffee',
  displayName: 'Coffee',
  colors: {
    primary: '#d4a574',
    secondary: '#b8956e',
    accent: '#f5deb3',
    muted: '#6b4423',
    border: '#8b6914',
    borderActive: '#d4a574',
    background: '#2d1810',
    statusInbox: '#d4a574',
    statusNext: '#b8956e',
    statusWaiting: '#daa520',
    statusSomeday: '#a0522d',
    statusDone: '#6b4423',
    text: '#d4a574',
    textMuted: '#8b6914',
    textSelected: '#f5deb3',
    textHighlight: '#d4a574',
    fnKeyLabel: '#3d2817',
    fnKeyText: '#d4a574',
  },
  borders: {
    main: 'round',
    modal: 'round',
    list: 'single',
  },
  style: {
    selectedPrefix: '❯ ',
    unselectedPrefix: '  ',
    tabActiveInverse: true,
    tabBrackets: ['', ''],
    headerUppercase: false,
    showFunctionKeys: false,
    loadingChars: ['☕', '○'],
  },
};

export const themes: Record<ThemeName, Theme> = {
  'modern': modernTheme,
  'norton-commander': nortonCommanderTheme,
  'dos-prompt': dosPromptTheme,
  'turbo-pascal': turboPascalTheme,
  'classic-mac': classicMacTheme,
  'apple-ii': appleIITheme,
  'commodore-64': commodore64Theme,
  'amiga-workbench': amigaWorkbenchTheme,
  'matrix': matrixTheme,
  'amber-crt': amberCrtTheme,
  'phosphor': phosphorTheme,
  'solarized-dark': solarizedDarkTheme,
  'solarized-light': solarizedLightTheme,
  'synthwave': synthwaveTheme,
  'paper': paperTheme,
  'coffee': coffeeTheme,
};

export const VALID_THEMES: ThemeName[] = [
  'modern',
  'norton-commander',
  'dos-prompt',
  'turbo-pascal',
  'classic-mac',
  'apple-ii',
  'commodore-64',
  'amiga-workbench',
  'matrix',
  'amber-crt',
  'phosphor',
  'solarized-dark',
  'solarized-light',
  'synthwave',
  'paper',
  'coffee',
];

export function getTheme(name: ThemeName): Theme {
  return themes[name] || modernTheme;
}

export function isValidTheme(name: string): name is ThemeName {
  return VALID_THEMES.includes(name as ThemeName);
}
