import type { Theme, ThemeName } from './types.js';

export const modernTheme: Theme = {
  name: 'modern',
  displayName: 'Modern',
  colors: {
    primary: 'green',
    secondary: 'cyan',
    accent: 'yellow',
    muted: 'gray',
    border: 'gray',
    borderActive: 'cyan',
    statusInbox: 'blue',
    statusNext: 'green',
    statusWaiting: 'yellow',
    statusSomeday: 'magenta',
    statusDone: 'gray',
    text: 'white',
    textMuted: '#999999',
    textSelected: 'cyan',
    textHighlight: 'green',
    fnKeyLabel: 'black',
    fnKeyText: 'cyan',
  },
  borders: {
    main: 'single',
    modal: 'round',
    list: 'single',
  },
  style: {
    selectedPrefix: '› ',
    unselectedPrefix: '  ',
    tabActiveInverse: true,
    tabBrackets: ['', ''],
    headerUppercase: false,
    showFunctionKeys: false,
    loadingChars: ['▪', '▫'],
  },
};

export const nortonCommanderTheme: Theme = {
  name: 'norton-commander',
  displayName: 'Norton Commander',
  colors: {
    primary: 'cyan',
    secondary: 'yellow',
    accent: 'white',
    muted: 'blue',
    border: 'cyan',
    borderActive: 'yellow',
    background: 'blue',
    statusInbox: 'white',
    statusNext: 'green',
    statusWaiting: 'yellow',
    statusSomeday: 'magenta',
    statusDone: 'gray',
    text: 'cyan',
    textMuted: 'blue',
    textSelected: 'yellow',
    textHighlight: 'white',
    fnKeyLabel: 'cyan',
    fnKeyText: 'white',
  },
  borders: {
    main: 'double',
    modal: 'double',
    list: 'double',
  },
  style: {
    selectedPrefix: '► ',
    unselectedPrefix: '  ',
    tabActiveInverse: true,
    tabBrackets: ['[', ']'],
    headerUppercase: true,
    showFunctionKeys: true,
    loadingChars: ['█', '░'],
  },
};

export const dosPromptTheme: Theme = {
  name: 'dos-prompt',
  displayName: 'DOS Prompt',
  colors: {
    primary: 'green',
    secondary: 'green',
    accent: 'white',
    muted: 'gray',
    border: 'green',
    borderActive: 'white',
    statusInbox: 'white',
    statusNext: 'green',
    statusWaiting: 'yellow',
    statusSomeday: 'gray',
    statusDone: 'gray',
    text: 'green',
    textMuted: 'gray',
    textSelected: 'white',
    textHighlight: 'green',
    fnKeyLabel: 'green',
    fnKeyText: 'white',
  },
  borders: {
    main: 'single',
    modal: 'single',
    list: 'single',
  },
  style: {
    selectedPrefix: '> ',
    unselectedPrefix: '  ',
    tabActiveInverse: false,
    tabBrackets: ['<', '>'],
    headerUppercase: true,
    showFunctionKeys: true,
    loadingChars: ['#', '-'],
  },
};

export const turboPascalTheme: Theme = {
  name: 'turbo-pascal',
  displayName: 'Turbo Pascal IDE',
  colors: {
    primary: 'yellow',
    secondary: 'white',
    accent: 'red',
    muted: 'cyan',
    border: 'white',
    borderActive: 'yellow',
    background: 'blue',
    statusInbox: 'white',
    statusNext: 'yellow',
    statusWaiting: 'red',
    statusSomeday: 'cyan',
    statusDone: 'gray',
    text: 'white',
    textMuted: 'cyan',
    textSelected: 'yellow',
    textHighlight: 'white',
    fnKeyLabel: 'red',
    fnKeyText: 'cyan',
  },
  borders: {
    main: 'double',
    modal: 'double',
    list: 'single',
  },
  style: {
    selectedPrefix: '» ',
    unselectedPrefix: '  ',
    tabActiveInverse: true,
    tabBrackets: ['[', ']'],
    headerUppercase: true,
    showFunctionKeys: true,
    loadingChars: ['█', '▒'],
  },
};

// Classic Macintosh System 7 style - monochrome elegance
export const classicMacTheme: Theme = {
  name: 'classic-mac',
  displayName: 'Classic Mac',
  colors: {
    primary: 'white',
    secondary: 'white',
    accent: 'white',
    muted: 'gray',
    border: 'white',
    borderActive: 'white',
    statusInbox: 'white',
    statusNext: 'white',
    statusWaiting: 'gray',
    statusSomeday: 'gray',
    statusDone: 'gray',
    text: 'white',
    textMuted: 'gray',
    textSelected: 'black',
    textHighlight: 'white',
    fnKeyLabel: 'black',
    fnKeyText: 'white',
  },
  borders: {
    main: 'single',
    modal: 'round',
    list: 'single',
  },
  style: {
    selectedPrefix: '☛ ',
    unselectedPrefix: '  ',
    tabActiveInverse: true,
    tabBrackets: ['', ''],
    headerUppercase: false,
    showFunctionKeys: false,
    loadingChars: ['◼', '◻'],
  },
};

// Apple II green phosphor monitor
export const appleIITheme: Theme = {
  name: 'apple-ii',
  displayName: 'Apple ][',
  colors: {
    primary: '#00ff00',
    secondary: '#00ff00',
    accent: '#00ff00',
    muted: '#008000',
    border: '#00ff00',
    borderActive: '#00ff00',
    statusInbox: '#00ff00',
    statusNext: '#00ff00',
    statusWaiting: '#008000',
    statusSomeday: '#008000',
    statusDone: '#004000',
    text: '#00ff00',
    textMuted: '#008000',
    textSelected: '#00ff00',
    textHighlight: '#00ff00',
    fnKeyLabel: '#004000',
    fnKeyText: '#00ff00',
  },
  borders: {
    main: 'single',
    modal: 'single',
    list: 'single',
  },
  style: {
    selectedPrefix: '] ',
    unselectedPrefix: '  ',
    tabActiveInverse: true,
    tabBrackets: ['[', ']'],
    headerUppercase: true,
    showFunctionKeys: false,
    loadingChars: ['▓', '░'],
  },
};

// Commodore 64 - iconic blue and light blue
export const commodore64Theme: Theme = {
  name: 'commodore-64',
  displayName: 'Commodore 64',
  colors: {
    primary: '#7869c4',
    secondary: '#9f9fff',
    accent: '#ffffff',
    muted: '#6c5eb5',
    border: '#7869c4',
    borderActive: '#9f9fff',
    background: '#40318d',
    statusInbox: '#9f9fff',
    statusNext: '#7fff7f',
    statusWaiting: '#ffff7f',
    statusSomeday: '#7f7fff',
    statusDone: '#6c5eb5',
    text: '#9f9fff',
    textMuted: '#6c5eb5',
    textSelected: '#ffffff',
    textHighlight: '#9f9fff',
    fnKeyLabel: '#40318d',
    fnKeyText: '#9f9fff',
  },
  borders: {
    main: 'single',
    modal: 'single',
    list: 'single',
  },
  style: {
    selectedPrefix: '▶ ',
    unselectedPrefix: '  ',
    tabActiveInverse: true,
    tabBrackets: ['<', '>'],
    headerUppercase: true,
    showFunctionKeys: true,
    loadingChars: ['●', '○'],
  },
};

// Amiga Workbench - orange, blue, white, black
export const amigaWorkbenchTheme: Theme = {
  name: 'amiga-workbench',
  displayName: 'Amiga Workbench',
  colors: {
    primary: '#ff8800',
    secondary: '#0055aa',
    accent: '#ffffff',
    muted: '#0055aa',
    border: '#ff8800',
    borderActive: '#ffffff',
    background: '#0055aa',
    statusInbox: '#ffffff',
    statusNext: '#ff8800',
    statusWaiting: '#ffcc00',
    statusSomeday: '#0088ff',
    statusDone: '#555555',
    text: '#ff8800',
    textMuted: '#0088ff',
    textSelected: '#ffffff',
    textHighlight: '#ff8800',
    fnKeyLabel: '#0055aa',
    fnKeyText: '#ff8800',
  },
  borders: {
    main: 'double',
    modal: 'single',
    list: 'single',
  },
  style: {
    selectedPrefix: '▸ ',
    unselectedPrefix: '  ',
    tabActiveInverse: true,
    tabBrackets: ['【', '】'],
    headerUppercase: false,
    showFunctionKeys: true,
    loadingChars: ['▰', '▱'],
  },
};

// Matrix - digital rain aesthetic
export const matrixTheme: Theme = {
  name: 'matrix',
  displayName: 'Matrix',
  colors: {
    primary: '#00ff00',
    secondary: '#00cc00',
    accent: '#ffffff',
    muted: '#003300',
    border: '#00ff00',
    borderActive: '#00ff00',
    statusInbox: '#00ff00',
    statusNext: '#00ff00',
    statusWaiting: '#00cc00',
    statusSomeday: '#009900',
    statusDone: '#003300',
    text: '#00ff00',
    textMuted: '#006600',
    textSelected: '#ffffff',
    textHighlight: '#00ff00',
    fnKeyLabel: '#003300',
    fnKeyText: '#00ff00',
  },
  borders: {
    main: 'single',
    modal: 'single',
    list: 'single',
  },
  style: {
    selectedPrefix: '⟩ ',
    unselectedPrefix: '  ',
    tabActiveInverse: false,
    tabBrackets: ['⟨', '⟩'],
    headerUppercase: false,
    showFunctionKeys: false,
    loadingChars: ['█', '▁'],
  },
};

// Amber CRT monitor
export const amberCrtTheme: Theme = {
  name: 'amber-crt',
  displayName: 'Amber CRT',
  colors: {
    primary: '#ffb000',
    secondary: '#ffb000',
    accent: '#ffd000',
    muted: '#805800',
    border: '#ffb000',
    borderActive: '#ffd000',
    statusInbox: '#ffd000',
    statusNext: '#ffb000',
    statusWaiting: '#cc8800',
    statusSomeday: '#996600',
    statusDone: '#664400',
    text: '#ffb000',
    textMuted: '#996600',
    textSelected: '#ffd000',
    textHighlight: '#ffb000',
    fnKeyLabel: '#664400',
    fnKeyText: '#ffb000',
  },
  borders: {
    main: 'single',
    modal: 'single',
    list: 'single',
  },
  style: {
    selectedPrefix: '→ ',
    unselectedPrefix: '  ',
    tabActiveInverse: true,
    tabBrackets: ['(', ')'],
    headerUppercase: true,
    showFunctionKeys: false,
    loadingChars: ['▮', '▯'],
  },
};

// Phosphor CRT with glow effect colors
export const phosphorTheme: Theme = {
  name: 'phosphor',
  displayName: 'Phosphor',
  colors: {
    primary: '#33ff33',
    secondary: '#66ff66',
    accent: '#99ff99',
    muted: '#116611',
    border: '#33ff33',
    borderActive: '#66ff66',
    statusInbox: '#66ff66',
    statusNext: '#33ff33',
    statusWaiting: '#99ff33',
    statusSomeday: '#33ff99',
    statusDone: '#116611',
    text: '#33ff33',
    textMuted: '#228822',
    textSelected: '#99ff99',
    textHighlight: '#66ff66',
    fnKeyLabel: '#116611',
    fnKeyText: '#33ff33',
  },
  borders: {
    main: 'round',
    modal: 'round',
    list: 'single',
  },
  style: {
    selectedPrefix: '◈ ',
    unselectedPrefix: '  ',
    tabActiveInverse: true,
    tabBrackets: ['', ''],
    headerUppercase: false,
    showFunctionKeys: false,
    loadingChars: ['◉', '◎'],
  },
};

// Solarized Dark - eye-friendly classic
export const solarizedDarkTheme: Theme = {
  name: 'solarized-dark',
  displayName: 'Solarized Dark',
  colors: {
    primary: '#268bd2',
    secondary: '#2aa198',
    accent: '#b58900',
    muted: '#586e75',
    border: '#586e75',
    borderActive: '#268bd2',
    background: '#002b36',
    statusInbox: '#268bd2',
    statusNext: '#859900',
    statusWaiting: '#b58900',
    statusSomeday: '#6c71c4',
    statusDone: '#586e75',
    text: '#839496',
    textMuted: '#586e75',
    textSelected: '#93a1a1',
    textHighlight: '#268bd2',
    fnKeyLabel: '#073642',
    fnKeyText: '#839496',
  },
  borders: {
    main: 'round',
    modal: 'round',
    list: 'single',
  },
  style: {
    selectedPrefix: '• ',
    unselectedPrefix: '  ',
    tabActiveInverse: true,
    tabBrackets: ['', ''],
    headerUppercase: false,
    showFunctionKeys: false,
    loadingChars: ['●', '○'],
  },
};

// Solarized Light
export const solarizedLightTheme: Theme = {
  name: 'solarized-light',
  displayName: 'Solarized Light',
  colors: {
    primary: '#268bd2',
    secondary: '#2aa198',
    accent: '#b58900',
    muted: '#93a1a1',
    border: '#93a1a1',
    borderActive: '#268bd2',
    background: '#fdf6e3',
    statusInbox: '#268bd2',
    statusNext: '#859900',
    statusWaiting: '#b58900',
    statusSomeday: '#6c71c4',
    statusDone: '#93a1a1',
    text: '#657b83',
    textMuted: '#93a1a1',
    textSelected: '#586e75',
    textHighlight: '#268bd2',
    fnKeyLabel: '#eee8d5',
    fnKeyText: '#657b83',
  },
  borders: {
    main: 'round',
    modal: 'round',
    list: 'single',
  },
  style: {
    selectedPrefix: '• ',
    unselectedPrefix: '  ',
    tabActiveInverse: true,
    tabBrackets: ['', ''],
    headerUppercase: false,
    showFunctionKeys: false,
    loadingChars: ['●', '○'],
  },
};

// Synthwave / Outrun - neon 80s aesthetic
export const synthwaveTheme: Theme = {
  name: 'synthwave',
  displayName: 'Synthwave',
  colors: {
    primary: '#ff00ff',
    secondary: '#00ffff',
    accent: '#ff00aa',
    muted: '#660066',
    border: '#ff00ff',
    borderActive: '#00ffff',
    background: '#1a0a2e',
    statusInbox: '#00ffff',
    statusNext: '#ff00ff',
    statusWaiting: '#ffff00',
    statusSomeday: '#ff6600',
    statusDone: '#660066',
    text: '#ff00ff',
    textMuted: '#9933ff',
    textSelected: '#00ffff',
    textHighlight: '#ff00ff',
    fnKeyLabel: '#330033',
    fnKeyText: '#00ffff',
  },
  borders: {
    main: 'double',
    modal: 'double',
    list: 'single',
  },
  style: {
    selectedPrefix: '◆ ',
    unselectedPrefix: '  ',
    tabActiveInverse: true,
    tabBrackets: ['「', '」'],
    headerUppercase: false,
    showFunctionKeys: true,
    loadingChars: ['◢', '◣'],
  },
};

// Paper - light minimal theme
export const paperTheme: Theme = {
  name: 'paper',
  displayName: 'Paper',
  colors: {
    primary: '#333333',
    secondary: '#555555',
    accent: '#0066cc',
    muted: '#999999',
    border: '#cccccc',
    borderActive: '#333333',
    background: '#ffffff',
    statusInbox: '#0066cc',
    statusNext: '#009933',
    statusWaiting: '#cc6600',
    statusSomeday: '#666699',
    statusDone: '#999999',
    text: '#333333',
    textMuted: '#999999',
    textSelected: '#000000',
    textHighlight: '#0066cc',
    fnKeyLabel: '#eeeeee',
    fnKeyText: '#333333',
  },
  borders: {
    main: 'single',
    modal: 'round',
    list: 'single',
  },
  style: {
    selectedPrefix: '▸ ',
    unselectedPrefix: '  ',
    tabActiveInverse: false,
    tabBrackets: ['', ''],
    headerUppercase: false,
    showFunctionKeys: false,
    loadingChars: ['■', '□'],
  },
};

// Coffee - warm brown tones
export const coffeeTheme: Theme = {
  name: 'coffee',
  displayName: 'Coffee',
  colors: {
    primary: '#d4a574',
    secondary: '#b8956e',
    accent: '#f5deb3',
    muted: '#6b4423',
    border: '#8b6914',
    borderActive: '#d4a574',
    background: '#2d1810',
    statusInbox: '#d4a574',
    statusNext: '#b8956e',
    statusWaiting: '#daa520',
    statusSomeday: '#a0522d',
    statusDone: '#6b4423',
    text: '#d4a574',
    textMuted: '#8b6914',
    textSelected: '#f5deb3',
    textHighlight: '#d4a574',
    fnKeyLabel: '#3d2817',
    fnKeyText: '#d4a574',
  },
  borders: {
    main: 'round',
    modal: 'round',
    list: 'single',
  },
  style: {
    selectedPrefix: '❯ ',
    unselectedPrefix: '  ',
    tabActiveInverse: true,
    tabBrackets: ['', ''],
    headerUppercase: false,
    showFunctionKeys: false,
    loadingChars: ['☕', '○'],
  },
};

// Nord - Arctic, north-bluish color palette
export const nordTheme: Theme = {
  name: 'nord',
  displayName: 'Nord',
  colors: {
    primary: '#88c0d0',
    secondary: '#81a1c1',
    accent: '#ebcb8b',
    muted: '#4c566a',
    border: '#4c566a',
    borderActive: '#88c0d0',
    background: '#2e3440',
    statusInbox: '#88c0d0',
    statusNext: '#a3be8c',
    statusWaiting: '#ebcb8b',
    statusSomeday: '#b48ead',
    statusDone: '#4c566a',
    text: '#eceff4',
    textMuted: '#4c566a',
    textSelected: '#88c0d0',
    textHighlight: '#a3be8c',
    fnKeyLabel: '#3b4252',
    fnKeyText: '#d8dee9',
  },
  borders: {
    main: 'round',
    modal: 'round',
    list: 'single',
  },
  style: {
    selectedPrefix: '❯ ',
    unselectedPrefix: '  ',
    tabActiveInverse: true,
    tabBrackets: ['', ''],
    headerUppercase: false,
    showFunctionKeys: false,
    loadingChars: ['●', '○'],
  },
};

// Dracula - Dark theme with vibrant colors
export const draculaTheme: Theme = {
  name: 'dracula',
  displayName: 'Dracula',
  colors: {
    primary: '#bd93f9',
    secondary: '#8be9fd',
    accent: '#ff79c6',
    muted: '#6272a4',
    border: '#6272a4',
    borderActive: '#bd93f9',
    background: '#282a36',
    statusInbox: '#8be9fd',
    statusNext: '#50fa7b',
    statusWaiting: '#ffb86c',
    statusSomeday: '#ff79c6',
    statusDone: '#6272a4',
    text: '#f8f8f2',
    textMuted: '#6272a4',
    textSelected: '#bd93f9',
    textHighlight: '#50fa7b',
    fnKeyLabel: '#44475a',
    fnKeyText: '#f8f8f2',
  },
  borders: {
    main: 'round',
    modal: 'round',
    list: 'single',
  },
  style: {
    selectedPrefix: '▸ ',
    unselectedPrefix: '  ',
    tabActiveInverse: true,
    tabBrackets: ['', ''],
    headerUppercase: false,
    showFunctionKeys: false,
    loadingChars: ['◆', '◇'],
  },
};

// Monokai - Classic editor theme with vibrant syntax colors
export const monokaiTheme: Theme = {
  name: 'monokai',
  displayName: 'Monokai',
  colors: {
    primary: '#f92672',
    secondary: '#66d9ef',
    accent: '#a6e22e',
    muted: '#75715e',
    border: '#75715e',
    borderActive: '#f92672',
    background: '#272822',
    statusInbox: '#66d9ef',
    statusNext: '#a6e22e',
    statusWaiting: '#e6db74',
    statusSomeday: '#ae81ff',
    statusDone: '#75715e',
    text: '#f8f8f2',
    textMuted: '#75715e',
    textSelected: '#f92672',
    textHighlight: '#a6e22e',
    fnKeyLabel: '#3e3d32',
    fnKeyText: '#f8f8f2',
  },
  borders: {
    main: 'single',
    modal: 'round',
    list: 'single',
  },
  style: {
    selectedPrefix: '» ',
    unselectedPrefix: '  ',
    tabActiveInverse: true,
    tabBrackets: ['', ''],
    headerUppercase: false,
    showFunctionKeys: false,
    loadingChars: ['▓', '░'],
  },
};

// Gruvbox - Retro groove color scheme
export const gruvboxTheme: Theme = {
  name: 'gruvbox',
  displayName: 'Gruvbox',
  colors: {
    primary: '#fe8019',
    secondary: '#fabd2f',
    accent: '#b8bb26',
    muted: '#665c54',
    border: '#665c54',
    borderActive: '#fe8019',
    background: '#282828',
    statusInbox: '#83a598',
    statusNext: '#b8bb26',
    statusWaiting: '#fabd2f',
    statusSomeday: '#d3869b',
    statusDone: '#665c54',
    text: '#ebdbb2',
    textMuted: '#928374',
    textSelected: '#fe8019',
    textHighlight: '#b8bb26',
    fnKeyLabel: '#3c3836',
    fnKeyText: '#ebdbb2',
  },
  borders: {
    main: 'single',
    modal: 'single',
    list: 'single',
  },
  style: {
    selectedPrefix: '▶ ',
    unselectedPrefix: '  ',
    tabActiveInverse: true,
    tabBrackets: ['[', ']'],
    headerUppercase: false,
    showFunctionKeys: false,
    loadingChars: ['█', '░'],
  },
};

// Tokyo Night - A clean dark theme inspired by Tokyo's night lights
export const tokyoNightTheme: Theme = {
  name: 'tokyo-night',
  displayName: 'Tokyo Night',
  colors: {
    primary: '#7aa2f7',
    secondary: '#bb9af7',
    accent: '#7dcfff',
    muted: '#565f89',
    border: '#565f89',
    borderActive: '#7aa2f7',
    background: '#1a1b26',
    statusInbox: '#7aa2f7',
    statusNext: '#9ece6a',
    statusWaiting: '#e0af68',
    statusSomeday: '#bb9af7',
    statusDone: '#565f89',
    text: '#c0caf5',
    textMuted: '#565f89',
    textSelected: '#7dcfff',
    textHighlight: '#9ece6a',
    fnKeyLabel: '#24283b',
    fnKeyText: '#c0caf5',
  },
  borders: {
    main: 'round',
    modal: 'round',
    list: 'single',
  },
  style: {
    selectedPrefix: '› ',
    unselectedPrefix: '  ',
    tabActiveInverse: true,
    tabBrackets: ['', ''],
    headerUppercase: false,
    showFunctionKeys: false,
    loadingChars: ['◉', '◎'],
  },
};

// Catppuccin - Soothing pastel theme (Mocha variant)
export const catppuccinTheme: Theme = {
  name: 'catppuccin',
  displayName: 'Catppuccin',
  colors: {
    primary: '#cba6f7',
    secondary: '#89b4fa',
    accent: '#f5c2e7',
    muted: '#6c7086',
    border: '#6c7086',
    borderActive: '#cba6f7',
    background: '#1e1e2e',
    statusInbox: '#89b4fa',
    statusNext: '#a6e3a1',
    statusWaiting: '#f9e2af',
    statusSomeday: '#f5c2e7',
    statusDone: '#6c7086',
    text: '#cdd6f4',
    textMuted: '#6c7086',
    textSelected: '#cba6f7',
    textHighlight: '#a6e3a1',
    fnKeyLabel: '#313244',
    fnKeyText: '#cdd6f4',
  },
  borders: {
    main: 'round',
    modal: 'round',
    list: 'single',
  },
  style: {
    selectedPrefix: '◆ ',
    unselectedPrefix: '  ',
    tabActiveInverse: true,
    tabBrackets: ['', ''],
    headerUppercase: false,
    showFunctionKeys: false,
    loadingChars: ['●', '○'],
  },
};

// Ocean - Deep sea inspired blue theme
export const oceanTheme: Theme = {
  name: 'ocean',
  displayName: 'Ocean',
  colors: {
    primary: '#00b4d8',
    secondary: '#0077b6',
    accent: '#90e0ef',
    muted: '#023e8a',
    border: '#0077b6',
    borderActive: '#00b4d8',
    background: '#03045e',
    statusInbox: '#00b4d8',
    statusNext: '#48cae4',
    statusWaiting: '#90e0ef',
    statusSomeday: '#ade8f4',
    statusDone: '#023e8a',
    text: '#caf0f8',
    textMuted: '#0077b6',
    textSelected: '#90e0ef',
    textHighlight: '#48cae4',
    fnKeyLabel: '#023e8a',
    fnKeyText: '#caf0f8',
  },
  borders: {
    main: 'round',
    modal: 'round',
    list: 'single',
  },
  style: {
    selectedPrefix: '≋ ',
    unselectedPrefix: '  ',
    tabActiveInverse: true,
    tabBrackets: ['〔', '〕'],
    headerUppercase: false,
    showFunctionKeys: false,
    loadingChars: ['◐', '◑'],
  },
};

// Sakura - Cherry blossom inspired pink theme
export const sakuraTheme: Theme = {
  name: 'sakura',
  displayName: 'Sakura',
  colors: {
    primary: '#ffb7c5',
    secondary: '#ff8fa3',
    accent: '#ffffff',
    muted: '#c9184a',
    border: '#ff8fa3',
    borderActive: '#ffb7c5',
    background: '#590d22',
    statusInbox: '#ffb7c5',
    statusNext: '#ff758f',
    statusWaiting: '#ffccd5',
    statusSomeday: '#ff4d6d',
    statusDone: '#800f2f',
    text: '#fff0f3',
    textMuted: '#a4133c',
    textSelected: '#ffffff',
    textHighlight: '#ff758f',
    fnKeyLabel: '#800f2f',
    fnKeyText: '#ffb7c5',
  },
  borders: {
    main: 'round',
    modal: 'round',
    list: 'single',
  },
  style: {
    selectedPrefix: '❀ ',
    unselectedPrefix: '  ',
    tabActiveInverse: true,
    tabBrackets: ['『', '』'],
    headerUppercase: false,
    showFunctionKeys: false,
    loadingChars: ['✿', '❀'],
  },
};

// MSX - Japanese retro computer style (TMS9918 palette)
export const msxTheme: Theme = {
  name: 'msx',
  displayName: 'MSX',
  colors: {
    primary: '#40b64a',
    secondary: '#5955df',
    accent: '#ffffff',
    muted: '#cacaca',
    border: '#40b64a',
    borderActive: '#73ce7c',
    background: '#000000',
    statusInbox: '#64daee',
    statusNext: '#40b64a',
    statusWaiting: '#ddce85',
    statusSomeday: '#b565b3',
    statusDone: '#cacaca',
    text: '#40b64a',
    textMuted: '#cacaca',
    textSelected: '#ffffff',
    textHighlight: '#73ce7c',
    fnKeyLabel: '#64daee',
    fnKeyText: '#000000',
  },
  borders: {
    main: 'single',
    modal: 'single',
    list: 'single',
  },
  style: {
    selectedPrefix: '> ',
    unselectedPrefix: '  ',
    tabActiveInverse: true,
    tabBrackets: ['[', ']'],
    headerUppercase: true,
    showFunctionKeys: true,
    loadingChars: ['■', '□'],
  },
};

// PC-98 - NEC PC-9801 style
export const pc98Theme: Theme = {
  name: 'pc-98',
  displayName: 'PC-98',
  colors: {
    primary: '#ffffff',
    secondary: '#00ffff',
    accent: '#ffff00',
    muted: '#808080',
    border: '#ffffff',
    borderActive: '#00ffff',
    background: '#000080',
    statusInbox: '#00ffff',
    statusNext: '#00ff00',
    statusWaiting: '#ffff00',
    statusSomeday: '#ff00ff',
    statusDone: '#808080',
    text: '#ffffff',
    textMuted: '#808080',
    textSelected: '#ffff00',
    textHighlight: '#00ffff',
    fnKeyLabel: '#00ffff',
    fnKeyText: '#ffffff',
  },
  borders: {
    main: 'single',
    modal: 'double',
    list: 'single',
  },
  style: {
    selectedPrefix: '▶ ',
    unselectedPrefix: '  ',
    tabActiveInverse: true,
    tabBrackets: ['【', '】'],
    headerUppercase: false,
    showFunctionKeys: true,
    loadingChars: ['●', '○'],
  },
};

// Mario - Nintendo's iconic plumber colors (bright, fun, colorful)
export const marioTheme: Theme = {
  name: 'mario',
  displayName: 'Mario',
  uiStyle: 'mario-block',
  colors: {
    primary: '#e52521',      // Mario's red cap
    secondary: '#fbd000',    // Coins, stars
    accent: '#43b047',       // Green pipe, 1UP mushroom
    muted: '#c9a36a',        // Brick block tan
    border: '#fbd000',       // Gold border like coins
    borderActive: '#e52521', // Red when active
    background: '#5c94fc',   // NES sky blue
    statusInbox: '#fbd000',  // Coin gold
    statusNext: '#43b047',   // 1UP green
    statusWaiting: '#f5a623', // Fire flower orange
    statusSomeday: '#049cd8', // Blue overalls
    statusDone: '#c9a36a',   // Brick tan
    text: '#ffffff',
    textMuted: '#c9a36a',
    textSelected: '#fbd000',
    textHighlight: '#e52521',
    fnKeyLabel: '#e52521',
    fnKeyText: '#ffffff',
  },
  borders: {
    main: 'bold',
    modal: 'bold',
    list: 'single',
  },
  style: {
    selectedPrefix: '🍄 ',   // Mushroom!
    unselectedPrefix: '   ',
    tabActiveInverse: true,
    tabBrackets: ['《', '》'],
    headerUppercase: true,
    showFunctionKeys: true,
    loadingChars: ['★', '☆'],
  },
};

// Dragon Quest - Classic JRPG style with titled boxes
export const dragonQuestTheme: Theme = {
  name: 'dragon-quest',
  displayName: 'Dragon Quest',
  uiStyle: 'titled-box',
  colors: {
    primary: '#ffffff',
    secondary: '#ffcc00',
    accent: '#ffcc00',
    muted: '#666666',
    border: '#ffffff',
    borderActive: '#ffcc00',
    background: '#000080',
    statusInbox: '#ffffff',
    statusNext: '#00ff00',
    statusWaiting: '#ffcc00',
    statusSomeday: '#00ccff',
    statusDone: '#888888',
    text: '#ffffff',
    textMuted: '#aaaaaa',
    textSelected: '#ffcc00',
    textHighlight: '#ffcc00',
    fnKeyLabel: '#000080',
    fnKeyText: '#ffffff',
  },
  borders: {
    main: 'round',
    modal: 'round',
    list: 'round',
  },
  style: {
    selectedPrefix: '▶ ',
    unselectedPrefix: '  ',
    tabActiveInverse: true,
    tabBrackets: ['「', '」'],
    headerUppercase: false,
    showFunctionKeys: false,
    loadingChars: ['●', '○'],
  },
};

export const themes: Record<ThemeName, Theme> = {
  'modern': modernTheme,
  'norton-commander': nortonCommanderTheme,
  'dos-prompt': dosPromptTheme,
  'turbo-pascal': turboPascalTheme,
  'classic-mac': classicMacTheme,
  'apple-ii': appleIITheme,
  'commodore-64': commodore64Theme,
  'amiga-workbench': amigaWorkbenchTheme,
  'matrix': matrixTheme,
  'amber-crt': amberCrtTheme,
  'phosphor': phosphorTheme,
  'solarized-dark': solarizedDarkTheme,
  'solarized-light': solarizedLightTheme,
  'synthwave': synthwaveTheme,
  'paper': paperTheme,
  'coffee': coffeeTheme,
  'nord': nordTheme,
  'dracula': draculaTheme,
  'monokai': monokaiTheme,
  'gruvbox': gruvboxTheme,
  'tokyo-night': tokyoNightTheme,
  'catppuccin': catppuccinTheme,
  'ocean': oceanTheme,
  'sakura': sakuraTheme,
  'msx': msxTheme,
  'pc-98': pc98Theme,
  'dragon-quest': dragonQuestTheme,
  'mario': marioTheme,
};

export const VALID_THEMES: ThemeName[] = [
  'modern',
  'norton-commander',
  'dos-prompt',
  'turbo-pascal',
  'classic-mac',
  'apple-ii',
  'commodore-64',
  'amiga-workbench',
  'matrix',
  'amber-crt',
  'phosphor',
  'solarized-dark',
  'solarized-light',
  'synthwave',
  'paper',
  'coffee',
  'nord',
  'dracula',
  'monokai',
  'gruvbox',
  'tokyo-night',
  'catppuccin',
  'ocean',
  'sakura',
  'msx',
  'pc-98',
  'dragon-quest',
  'mario',
];

export function getTheme(name: ThemeName): Theme {
  return themes[name] || modernTheme;
}

export function isValidTheme(name: string): name is ThemeName {
  return VALID_THEMES.includes(name as ThemeName);
}
